services:
  task_backend:
    container_name: task_backend
    build:
      context: .
      dockerfile: Dockerfile.local
    command: bash ./start-local.sh
    restart: always
    env_file:
      - .env
    depends_on:
      - task_db
    logging:
      driver: "json-file"
      options:
        max-size: 128m
    volumes:
      - ./deploy:/app/deploy
      - ./:/app
    ports:
      - "8000:8000"


  task_db:
    container_name: task_db
    image: postgres:15-alpine
    restart: always
    command: [ "postgres", "-c", "log_statement=all" ]
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./volumes/postgresql/pg-data:/var/lib/postgresql/data

volumes:
  task_backend:
  task_db:
